<?php

//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(

//MENSAJES BASE DE DATOS
 'Fallo al conectar a MySQL: (' => 'Fallo al conectar a MySQL: (',
 'La contraseña para este usuario es errónea' => 'La contraseña para este usuario es errónea',
 'El usuario no existe' => 'El usuario no existe',
 'No se ha podido conectar con la base de datos' => 'No se ha podido conectar con la base de datos',
 'Inserción realizada con éxito' => 'Inserción realizada con éxito',
 'El usuario ya existe en la base de datos' => 'El usuario ya existe en la base de datos',
 'Introduzca un valor para username del usuario' => 'Introduzca un valor para username del usuario',
 'Error en la consulta sobre la base de datos' => 'Error en la consulta sobre la base de datos',
 'El usuario se ha modificado con éxito' => 'El usuario se ha modificado con éxito',
 'El usuario ha sido borrado correctamente' => 'El usuario ha sido borrado correctamente',
 'Ya existe un Usuario con ese userName' => 'Ya existe un Usuario con ese User',
 'Ya existe un Usuario con ese DNI' => 'Ya existe un Usuario con ese DNI',
 'Ya existe un Usuario con ese E-mail' => 'Ya existe un Usuario con ese E-mail',
 'No se ha podido conectar con la base de datos.' => 'No se ha podido conectar con la base de datos.',
 'Error en la consulta sobre la base de datos.' => 'Error en la consulta sobre la base de datos.',
 'No se puede borrar porque no existe esa Alerta.' => 'No se puede borrar porque no existe esa Alerta.',
 'La Alerta fue borrada con éxito.' => 'La Alerta fue borrada con éxito.',
 'No tienes los permisos necesarios' => 'No tienes los permisos necesarios',
 'Debe seleccionar un Curso' => 'Debe seleccionar un Curso',
 'NumSesiones' => 'Número de Calendarios',

//MENU
 'Iniciar Sesion' => 'Iniciar Sesion',
 'Usuario' => 'Usuario',
 'Cerrar Sesión' => 'Cerrar Sesión',
 'Cuenta' => 'Cuenta',
 'Mi Perfil' => 'Mi Perfil',
 'Gestión de Usuarios' => 'Usuarios',
 'Gestión de Alertas' => 'Alertas',
 'Gestión de Calendarios' => 'Calendarios',
 'Gestión de Asignaturas' => 'Asignaturas',
 'Gestión de Cursos' => 'Cursos',
    
//Acciones
 'Volver' => 'Volver',
 'Insertar' => 'Insertar',
 'Modificar' => 'Modificar',
 'Consultar' => 'Consultar',
 'Borrar' => 'Borrar',
 'Ver' => 'Ver',
 'Seleccionar' => 'Seleccionar',
 'Cerrar' => 'Cerrar',
 'Guardar' => 'Guardar',
 'Asignar' => 'Asignar',
 'ver' => 'ver',
 
//USUARIOS
 'username' => 'Usuario',
 'password' => 'Contraseña',
 'newPassword' => 'Contraseña Nueva',
 'nombre' => 'Nombre',
 'apellidos' => 'Apellidos',
 'tipoUsuario' => 'Tipo Usuario',
 'dni' => 'DNI',
 'niu' => 'NIU',
 'fechaNac' => 'Fecha Nac.',
 'email' => 'Email',
 'addAdministrador' => 'Añadir Administrador',
 'Administrador' => 'Administrador',
 'Estudiante' => 'Estudiante',
 'Insertar usuario' => 'Insertar Usuario',
 'Insertar Usuario' => 'Insertar Usuario',
 'Insertar Administrador' => 'Insertar Administrador',
 'Modificar Usuario' => 'Modificar Usuario',
 'Eliminar Usuario' => 'Eliminar Usuario',
 'Eliminar Administrador' => 'Eliminar Administrador',
 'Ver Usuario' => 'Ver Usuario',
 'Modificar usuario' => 'Modificar Usuario',
 

//Alertas
 'idAlerta' => 'ID',
 'fechaHora' => 'Fecha',
 'asuntoAlerta' => 'Asunto',
 'Descripción' => 'Descripción',
 'descripcionAlerta' => 'Descripción',
 'Ver Alerta' => 'Ver Alerta',
 'Insertar Alerta' => 'Crear Alerta',
 'Borrar Alerta' => 'Borrar Alerta',
 'La alerta fue borrada con éxito.' => 'La alerta fue borrada con éxito',
 'No se ha podido conectar con la base de datos en INSERT calendario_horas.' => 'No se pudo crear la Alerta porque no existe ese día en el calendario.',
 'Asunto' => 'Asunto',
 'Fecha' => 'Fecha',
 'Hora' => 'Hora',
 'Dias' => 'Dias',
 'Mensaje' => 'Mensaje',
 'Crear' =>'Nueva Alerta',
 'Aviso' =>'Introduce cuantos días antes quieres que el sistema te recuerde este evento.',

 
//Calendarios

 'Monday' => 'Lunes',
 'Tuesday' => 'Martes',
 'Wednesday' => 'Miercoles',
 'Thursday' => 'Jueves',
 'Friday' => 'Viernes',
 'Saturday' => 'Sabado',
 'Sunday' => 'Domingo',
 'Anterior Semana' => 'Anterior Semana',
 'Próxima Semana' => 'Próxima Semana',
 'Filtrar' => 'Filtrar',
 'Examen' => 'Examen:',
 'nombreCalendario' => 'Nombre',
 'idCalendario' => 'ID Calendario',
 'Modificar calendario' => 'Modificar Calendario',
 'Se ha insertado con éxito' => 'Se ha insertado con éxito',
 'Iniciar sesion' => 'Iniciar sesión',
 'IniciarSesion' => 'Iniciar Sesión',
 'El calendario se ha modificado con éxito.' => 'El calendario se ha modificado con éxito.',

//Asignaturas
 'nombreAsignatura' => 'Nombre de la Asignatura',
 'asignaturanombreCurso' => 'Nombre Asignatura',
 'descripcionAsignatura' => 'Descripción de la Asignatura',
 'asignaturadescCurso' => 'Descripción Asignatura',
 'saveform' => 'Guardar',
 'newAsignatura' => 'Nueva Asignatura',
 'asignaturanombre' => 'Nombre',
 'asignaturadescripcion' => 'Descripción',
 'asignaturamodificar' => 'Modificar',
 'asignaturaeliminar' => 'Eliminar',
 'Eliminar Asignatura' => 'Eliminar Asignatura',
 
//Cursos
 'nombreCurso2' => 'Nombre del Curso',
 'descripcionCurso2' => 'Descripción del Curso',
 'cursoname' => 'Nombre del Curso',
 'cursodesc' => 'Descripción del Curso',
 'savecurso' => 'Guardar',
 'newcurso' => 'Nuevo Curso',
 'obtenerCurso' => 'Importar Curso',
 'asignarcurso' => 'Asignar Asignaturas a Curso',
 'seleccionaCurso' => 'Selecciona el Curso del que quieres importar únicamente sus asignaturas',
 'ó' => 'ó',
 'closecurso' => 'Cerrar',
 'cursoname2' => 'Nombre',
 'cursodesc2' => 'Descripción',
 'cursoasignar' => 'Asignar Asignaturas',
 'cursomodificar' => 'Modificar',
 'cursoeliminar' => 'Eliminar',
 'Eliminar Curso' => 'Eliminar Curso',
 'Cursos' => 'Cursos',
 'nombreCurso' => 'Nombre del Curso',
 'descripcionCurso' => 'Descripción',
 'AñadirAsignatura' => 'Añadir Asignatura',
 'AsignarAsignaturas' => 'Asignar Asignaturas',
 'Asignatura'=>'Asignatura',
 'Guardar'=>'Guardar'

    
    
);
?>
