<?php

//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(

//MENSAJES BASE DE DATOS
'La actividad grupal fue borrada con exito'=> 'The group activity has been deleted successfully',
'Fallo al conectar a MySQL' => 'Fail to connect to MySQL',
 'La contraseña para este usuario es errónea' => 'The password for this user is wrong',
 'El usuario no existe' => 'This User does not exist',
 'No se ha podido conectar con la base de datos' => 'Unable to connect to the database',
 'Inserción realizada con éxito' => 'Insertion made successfully',
 'El usuario ya existe en la base de datos' => 'This user already exists in the database',
 'Introduzca un valor para username del usuario' => 'Enter a value for the user`s username',
 'Error en la consulta sobre la base de datos' => 'Error in the query on the database',
 'El usuario se ha modificado con éxito' => 'The user has been modified successfully',
 'El usuario ha sido borrado correctamente' => 'The user has been deleted correctly',
 'Solicitud aceptada' => 'Request accepted',
 'Solicitud rechazada' => 'Rejected Request',
 'No hay plazas para esa actividad' => 'There are no places for this activity',
 'No existe la inscripcion' => 'There is no registration',
 'Ya existe un Usuario con ese userName' => 'A user with that username already exists',
 'Ya existe un Usuario con ese DNI' => 'A user with that NID already exists',
 'Ya existe un Usuario con ese E-mail' => 'A user with that E-mail already exists',
 'VerTablas' => 'Assigned Tables',
 'La tabla ya ha sido asignada a este usuario' => 'The table has already been assigned to this athlete',
 'La tabla se ha asignado correctamente' => 'The table has been assigned correctly',
 'Ya han sido asignadas 5 tablas para este deportista' => '5 tables have already been assigned for this athlete',
 'Error al acepar la inscripcion' => 'Error accepting the registration',
 'MandarSolicitud' => 'Request',
 'No se ha podido conectar con la base de datos.' => 'Unable to connect database',
 'Error en la consulta sobre la base de datos.' => 'Unable to connect database',
 'La sesion se ha modificado con éxito' => 'Session has been modified successfully',
 'No se puede borrar porque no existe esa notificacion.' => 'The notification doesnt exist',
 'La notificacion fue borrada con éxito.' => 'Notification has been deleted',
 'La actividad grupal se ha modificado con exito' => 'The group activity has been modified successfully',
 'Ya existe una actividad en esta fecha, instalacion y horario o el monitor esta ocupado' => 'An activity already exists on this date, installation and schedule or the monitor is busy',
 'Solicitud tramitada' => 'Application processed successfully',
 'Añadida con exito' => 'Successfully added',
 'La actividad grupal fue borrada con éxito' => 'Deleted successfully',
 'No se puede borrar porque no existe esa actividad grupal' => 'There is no group activity',
 'La actividad individual fue borrada con exito' => 'The individual activity was successfully erased',
 'La actividad individual ya existe en la base de datos' => 'The individual activity already exists in the database',
 'No se puede borrar porque no existe esa actividad individual' => 'It can not be deleted because there is no such individual activity',
 'La actividad individual se ha modificado con exito' => 'The individual activity has been modified successfully',
 'No tienes los permisos necesarios' => 'You do not have the necessary permits',
 'Debe seleccionar una tabla' => 'You must select a table',
 'EstadísticasMuevet' => 'System Stats',
 'ActividadMas' => 'Activity/ies with more enrolled',
 'ActividadMenos' => 'Activity/ies with less enrolled',
 'PlazasOcupadas' => 'Inscribed',
 'Ocupacion' => 'Occupation',
 'EntrenadorMas' => 'Coach/s who teaches more classes',
 'EntrenadorMenos' => 'Coach/s who teaches less classes',
 'NumActividadesEntrenador' => 'Number of Activities taught',
 'DeportistaMas' => 'Athlete with more sessions',
 'NumSesiones' => 'Number of sessions',
 'DeportistaMasActividades' => 'Athlete enrolled in more activities',
 'NumActividades' => 'Number of Activities',
 'VerInscritos' => 'Inscribed',
  'NoHayPlazas'=>'Any Sites',


//MENU DEFAULTS (LOGIN Y SIN LOGIN)
'Iniciar Sesion' => 'Sign In',
 'Cerrar Sesión' => 'Sign Out',
 'Cuenta' => 'Account',
 'Mi Perfil' => 'My profile',
 'Gestión de Usuarios' => 'Users',
 'Gestión de Entrenadores' => 'Coachs',
 'Gestión de Deportistas' => 'Athletes',
 'Gestión de Instalaciones' => 'Facilities',
 'Gestión de Actividades Grupales' => 'Group Activities',
 'Gestión de notificaciones' => 'Notifications',
 'Gestión de sesiones' => 'Sessions',
 'Gestión de Inscripciones' => 'Inscription',
 'Gestión de ejercicios' => 'Exercises',
 'Gestión de tablas' => 'Tables',
 'Gestión de Actividades' => 'Activities',
 'Gestión de Actividades Grupales' => 'Group',
 'Gestión de Actividades Individuales' => 'Individuals',
  'Gestión de Estadisticas' =>'Stats',
 'Entrenamiento' => 'Training',
 'MisActividades' => 'My Activities',
 'Estadisticas' => 'Stats',
//Acciones
'Volver' => 'Return',
 'Insertar' => 'Add',
 'Modificar' => 'Edit',
 'Consultar' => 'Consult',
 'Borrar' => 'Delete',
 'Seleccionar' => 'Select',
 'Ver' => 'See',
 'Consultar' => 'Consult',
 'AsignarT' => 'Assign Table',
 'SeleccionaTabla' => 'Select Tables',
 'AsignarTablaDeportista' => 'Assign Table to an Athlete',
 'Cerrar' => 'Close',
 'Guardar' => 'Save',
 'Asignar' => 'Assign',
 'Ver1' => 'Ver1',
 'VerDeportistas' => 'See Athletes',
 'Desasignar' => 'Unassign',
 'AñadirTabla'=> 'Add table',
  'AsignarEjercicios'=>'Assign Exercises',
//USUARIOS
'userName' => 'User',
 'password' => 'Password',
 'newPassword' => 'New Password',
 'nombre' => 'Firt Name',
 'apellidos' => 'Last Name',
 'tipoUsuario' => 'Type',
 'dni' => 'NID',
 'fechaNac' => 'Birthdate',
 'telefono' => 'Phone',
 'direccion' => 'Addres',
 'email' => 'E-mail',
 'foto' => 'Photo',
 'Administrador' => 'Administrator',
 'Entrenador' => 'Coach',
 'Deportista' => 'Athlete',
 'Insertar usuario' => 'Add User',
 'Insertar Administrador' => 'Add Administrator',
 'Modificar Administrador' => 'Edit Administrator',
 'Eliminar Administrador' => 'Delete Administrator',
 'Modificar usuario' => 'Edit User',
 'Ver Administrador' => 'See Administrator',
 'InsertarSesion'=>'Finalize',
 'IniciarSesion' =>'Start Session',
//ENTRENADOR
'cuentaBanc' => 'Bank Account',
 'Insertar entrenador' => 'Add Coach',
 'Modificar entrenador' => 'Edit Coach',
 'Eliminar Entrenador' => 'Delete Coach',
 'Ver Entrenador' => 'See Coach',
 'VerActividadesImpartidas' => 'Imparted Activities',
//DEPORTISTA
'metodoPago' => 'Credit Card',
 'tipoDeportista' => "Athlete's Type",
 'PEF' => 'PEF',
 'TDU' => 'TDU',
 'Insertar deportista' => 'Add Athlete',
 'Modificar deportista' => 'Edit Athlete',
 'Eliminar Deportista' => 'Delete Athlete',
 'Ver Deportista' => 'See Athlete',
 'VerEstadisticas' => 'Statistics',
 'AsignarT' => 'AssignTable',
//INSCRIPCIONES
'GrupalesPendientes' => 'Group Activities Earrings',
 'IndividualesPendientes' => 'Individuals Activities Earrings',
 'nombreActividadGrupal' => 'Activity',
 0 => 'Pending Request',
 1 => 'Pending request',
 'plazasDisponibles' => 'Sites',
 'estado' => 'State',
 'Aceptar' => 'Accept',
 'Rechazar' => 'Reject',
 'MandarSolicitud' => 'Request',
 'EnTramite' => 'In process',
 'YaInscrito' => 'Already registered',
//NOTIFICACION
'idNotificacion' => 'idNotificacion',
 'remitenteNotificacion' => 'Sender',
 'destinatarioNotificacion' => 'Addressee',
 'fechaHoraNotificacion' => 'Dare',
 'asuntoNotificacion' => 'Affair',
 'mensajeNotificacion' => 'Message',
 'Ver Notificacion' => 'See Notification',
 'Insertar Notificacion' => 'Insert notification',
 'Borrar notificación' => 'Delete notification',
 'La notificación fue borrada con éxito.' => 'Notification succesfully deleted.',
 'Remitente' => 'Sender',
 'Asunto' => 'Affair',
 'Fecha' => 'Date',
 'Mensaje' => 'Message',
 'Crear'=>'Send',
  'Enviados' => 'Sended',
 'Recibidos' => 'Received', 
 'Notificaciones enviadas' => 'Notifications sended',
 'Notificaciones recibidas' => 'Notifications received',
//SESIONES

'nombreTabla' => 'Table',
 'nombreActividadIndividual' => 'Activity',
 'idTabla' => 'Table',
 'idActividadIndividual' => 'Activity',
 'comentarioSesion' => 'Commentary',
 'fechaSesion' => 'Date',
 'horaInicio' => 'Start',
 'horaFin' => 'Edn',
 'Modificar sesion' => 'Modify Session',
 'Consultar sesiones por fecha' => 'Consult sessions by date',
 'IniciarSesion' => 'New session',
 'Finalizar Sesion' => 'Finish Session',
 'Realizando tabla' => 'TABLE OF THE SESSION',
 'Actividad' => 'ACTIVITY',
 'La sesion se ha modificado con éxito.' => 'Session succesfully modified.',
//GESTION DE EJERCICIOS
'ejercicioname' => 'Work Name',
 'ejerciciodescription' => 'Work Description',
 'gifejercicio' => 'URL for Work´s GIF image',
 'previsualizacion' => 'GIF Previsualization',
 'howtoprev' => 'To load the GIF image, insert the url and key Tab',
 'saveform' => 'Save',
 'newejercicio' => 'Insert Work',
 'ejercicionametabla' => 'Name',
 'ejerciciodesctabla' => 'Description',
 'ejerciciogiftabla' => 'Execution',
 'ejerciciomodificar' => 'Modify',
 'ejercicioeliminar' => 'Delete',
//GESTION DE TABLAS
'tablaname' => 'Table Name',
 'tabladesc' => 'Table Description',
 'savetabla' => 'Save',
 'newtabla' => 'Insert Table',
 'asignartabla' => 'Assign Works to Table',
 'seleccionaejercicios' => 'Select Works (ctrl for multiselect)',
 'closetabla' => 'Close',
 'tablaname2' => 'Name',
 'tabladesc2' => 'Description',
 'tablaasignar' => 'Assign Works',
 'tablamodificar' => 'Modify',
 'tablaeliminar' => 'Delete',
 'Personalizada' => 'Personalized',
 'Estandar' => 'Standard',
 'tablaTipo' => 'Type of Table',
 'tipo' => 'Type',
 'Tablas' => 'Tables',
 'descripcionTabla' => 'Description',
  'AñadirEjercicio' => 'Add Exercise',
 'Ejercicio'=>'Exersice',
 'NumSeries'=>'Num. Series',
 'NumRepeticiones'=>'Num. Repetitions',
 'Duracion'=>'Duration',
 'Guardar'=>'Save',
//ACTIVIDADES GRUPALES

'nombreActividadGrupal' => 'Activity Name',
 'descripcionActividadGrupal' => 'Description',
 'numPlazasActividadGrupal' => 'Places',
 'idActividadGrupal' => 'ID',
 'username' => 'Teacher',
 'idInstalacion' => 'Installation',
 'Modificar Actividad Grupal' => 'Modify Individual Activity',
 'Insertar Actividad Grupal' => 'Add Group Activity',
 'Borrar Actividad Grupal' => 'Delete Group Activity',
 'Consultar Actividades Grupales' => 'Consult Group Activity',
 'Ver Actividad Grupal' => 'See Group Activity',
 'ActividadesGrupales' => 'Activities',
 'VerMonitor' => 'SeeMonitor',
 'diaActividadGrupal' => 'Day',
 'horaInicioActividadGrupal' => 'Start Time',
 'horaFinActividadGrupal' => 'End Time',
 'fechaInicioActividadGrupal' => 'Start Date',
 'fechaFinActividadGrupal' => 'End Date',
 'Lunes' => 'Monday',
 'Martes' => 'Tuesday',
 'Miércoles' => 'Wednesday',
 'Jueves' => 'Thursday',
 'Viernes' => 'Friday',
 'DesasignarActividad' => 'Unassign Activity',
//ACTIVIDADES INDIVIDUALES

'nombreActividadIndividual' => 'Name',
 'descripcionActividadIndividual' => 'Description',
 'Modificar Actividad Individual' => 'Modify Individual Activity',
 'Insertar Actividad Individual' => 'Insert Individual Activity',
 'Borrar Actividad Individual' => 'Delete Individual Activity',
 'Consultar Actividades Individuales' => 'Consult Individual Activities',
 'Ver Actividad Individual' => 'See Individual Activity',
//ESTADISTICAS    
'Estadisticas' => 'Statistics of user sessions ',
 'EstadísticasMuevet' =>'System Stats',
    
    
    
//INSTALACIONES

'nombreInstalacion' => 'Name',
'descripcionInstalacion' =>'Description',
'aforoInstalacion' =>'Gauging',
'idInstalacion' => 'ID',
'Modificar Instalacion' => 'Modify Installation',
'Insertar Instalacion' => 'Insert Installation',
'Borrar Instalacion' => 'Delete Installation',
'Consultar Instalaciones' => 'Consult Installation',
'Ver Instalacion' => 'See Installation',
'La instalacion fue borrada con exito' => 'The installation was successfully deleted',
'La instalacion ya existe en la base de datos' => 'The installation already exists in the database',
'No se puede borrar porque no existe esa instalacion' => 'It can not be deleted because there is no such installation',
'La instalacion se ha modificado con exito' => 'The installation has been successfully modified',
'No se puede borrar porque no existe esa instalacion' => 'It can not be deleted because that installation does not exist',
'Añadida con exito'=>'The installation has been successfully added'
 )
?>
