<?php
//CADENAS UTILIZADAS EN CASTELLANO
$strings = array(

//MENSAJES BASE DE DATOS
     'deportista'=>'deportista',
'Fallo al conectar a MySQL: (' => 'Erro ao conectar a MySQL',
'La contraseña para este usuario es errónea' =>'A contrasinal pra este usuario é errónea',
'El usuario no existe' => 'O usuario non existe',
'No se ha podido conectar con la base de datos' => 'Non se pudo conectar coa base de datos',
'Inserción realizada con éxito'=>'Inserción realizada con éxito',
'El usuario ya existe en la base de datos' => 'O usuario xa existe',
'Introduzca un valor para username del usuario' => 'Introduzca un valor para o username do usuario',
'Error en la consulta sobre la base de datos' => 'Error na consulta sobre a base de datos',
'El usuario se ha modificado con éxito'=>'O usuario modificouse con éxito',
'El usuario ha sido borrado correctamente' => 'O usuario foi borrado correctamente',
'Solicitud aceptada' => 'Solicitude aceptada',
'Solicitud rechazada' => 'Solicitude rechazada',
'No hay plazas para esa actividad' => 'Non hay prazas para dita actividade',
'No existe la inscripcion' => 'Non existe a solicitude',
'Ya existe un Usuario con ese userName' => 'Xa existe un Usuario con ise User',
'Ya existe un Usuario con ese DNI' => 'Xa existe un Usuario con ise DNI',
'Ya existe un Usuario con ese E-mail' =>'Xa existe un Usuario con ise E-mail',
 'La tabla ya ha sido asignada a este usuario' => 'A táboa xa foi asinada a este deportista',
'La tabla se ha asignado correctamente' => 'A táboa asinouse correctamente',
'Ya han sido asignadas 5 tablas para este deportista' => 'Xa foron asinadas 5 táboas para este deportista',
'Error al acepar la inscripcion' => 'Erro ao acepar a inscripcion',
'MandarSolicitud' => 'Solicitar',   
'No se ha podido conectar con la base de datos.' => 'Non se pudo conectar coa base de datos' , 
'Error en la consulta sobre la base de datos.' => 'Erro na consulta sobre a base de datos.',
'La sesion se ha modificado con éxito' => 'A sesion foi modificada con éxito',
'No se puede borrar porque no existe esa notificacion.' => 'Non se pode borrar porque non existe.',
'La notificacion fue borrada con éxito.' => 'A notificación foi borrada con éxito.',  
'No tienes los permisos necesarios' => 'Careces dos permisos necesarios',
'Debe seleccionar una tabla' =>'Debe seleccionar unha táboa',
    'EstadísticasMuevet' =>'Estadísticas do Sistema',
    'ActividadMas' => 'Actividad/es con máis inscritos',
    'ActividadMenos' =>'Actividad/es con menos inscritos',
    'PlazasOcupadas' =>'Inscritos',
    'Ocupacion' =>'Ocupación',
    'EntrenadorMas' => 'Entrenador/es que máis clases imparte',
    'EntrenadorMenos' => 'Entrenador/es que menos clases imparte',
    'NumActividadesEntrenador' =>'Número de Actividades impartidas',
    'DeportistaMas' =>'Deportista con máis sesións',
    'NumSesiones' => 'Número de sesións',
    'DeportistaMasActividades' => 'Deportista inscrito en máis actividades',
    'NumActividades' =>'Número de Actividades',
    'VerInscritos' =>'Inscritos',    
    'NoHayPlazas'=>'Prazas agotadas',
    
//MENU DEFAULTS (LOGIN Y SIN LOGIN)
'Iniciar Sesion' => 'Iniciar Sesion',
'Usuario' => 'Usuario',
'Cerrar Sesión' => 'Cerrar Sesión',
'Cuenta' => 'Conta',
'Mi Perfil' => 'Meu Perfil',
'Gestión de Usuarios' => 'Usuarios',
'Gestión de Entrenadores' => 'Adestradores',
'Gestión de Deportistas' => 'Deportistas',
'Gestión de Instalaciones' => 'Instalacións',
'Gestión de notificaciones' => 'Notificacións',
'Gestión de sesiones' => 'Sesións',
'Gestión de Inscripciones' => 'Inscripcións',
'Gestión de ejercicios' => 'Exercicios',
'Gestión de tablas' => 'Táboas',
'Gestión de Actividades' => 'Actividades',
'Gestión de Actividades Grupales' => 'Grupais',
'Gestión de Actividades Individuales' => 'Individuais',
 'Gestión de Estadisticas' =>'Estadísticas',
'Entrenamiento' => 'Adestramento',
'MisActividades' => 'As miñas Actividades',
'Estadisticas' =>'Estadisticas',



//Acciones
'Volver' => 'Volver',
'Insertar' =>'Insertar',
'Modificar' => 'Modificar',
'Consultar' => 'Consultar',
'Borrar' => 'Borrar',
'Ver'=>'Ver',
'Consultar' => 'Consultar',
'Seleccionar'=> 'Seleccionar',
'AsignarT' => 'Asignar Táboa',
'SeleccionaTabla' => 'Selecciona as Táboas',
'AsignarTablaDeportista' => 'Asinar táboas a un deportista',
'Cerrar' => 'Cerrar',
'Guardar' => 'Gardar',
'Asignar' => 'Asinar',
'Desasignar' => 'Desasinar',
'Ver1' => 'Ver1',
'VerDeportistas' => 'Ver Deportistas',
'InsertarSesion'=>'Finalizar',
'IniciarSesion' =>'Iniciar Sesión',
'AñadirTabla'=> 'Añadir Táboa',
    
//USUARIOS
'userName' => 'Usuario',
'password'=>'Contrasinal',
'newPassword'=>'Nova Contrasinal',
'nombre' => 'Nome',
'apellidos' => 'Apelidos',
'tipoUsuario' => 'Tipo',
'dni' => 'DNI',
'fechaNac' => 'Data de Nacemento',
'telefono' => 'Teléfono',
'direccion' => 'Dirección',
'email' => 'Email',
'foto' => 'Foto',
'Administrador' => 'Administrador',
'Entrenador' => 'Entrenador',
'Deportista' => 'Deportista',
'Insertar usuario' => 'Insertar Usuario',
'Insertar Administrador' => 'Insertar Administrador',
'Modificar Administrador' => 'Modificar Administrador',
'Eliminar Administrador' => 'Eliminar Administrador',
'Ver Administrador' => 'Ver Administrador',
'Modificar usuario'=>'Modificar Usuario',

    
//ENTRENADOR
'cuentaBanc' => 'Conta Bancaria',
'Insertar entrenador' => 'Insertar Adestrador',
'Modificar entrenador' => 'Modificar Adestrador',
'Eliminar Entrenador' => 'Eliminar Adestrador',
'Ver Entrenador' => 'Ver Adestrador',
'VerActividadesImpartidas' =>'Actividades Impartidas',   
    
//DEPORTISTA
'metodoPago' =>'Tarxeta de Crédito',
'tipoDeportista' => 'Tipo de Deportista',
'PEF' => 'PEF',
'TDU'=>'TDU',
'Insertar deportista' => 'Insertar Deportista',
'Modificar deportista' => 'Modificar Deportista',
'Eliminar Deportista' => 'Eliminar Deportista',
'Ver Deportista' => 'Ver Deportista',
'VerTablas' => 'Táboas asignadas',
'VerEstadisticas' =>'Estadísticas',
'AsignarT' => 'AsinarTaboa',
 

//INSCRIPCIONES
'Pendientes' => 'Pendientes',
'nombreActividadGrupal'=> 'Actividade',
0 => 'Solicitude Pendiente',
1 => 'Solicitude Aceptada',
'plazasDisponibles' => 'Prazas',
'estado' => 'Estado',
'Aceptar' => 'Aceptar',
'Rechazar' => 'Rechazar', 
'Solicitud tramitada' => 'Solicitude tramitada con éxito',
'Ya existe esta solicitud' => 'Xa existe esta solicitude',
'MandarSolicitud' => 'Solicitar',
'EnTramite' => 'En trámite',
'YaInscrito' => 'Xa Inscrito',
    
    
    
//NOTIFICACION
'idNotificacion' => 'idNotificacion',
'remitenteNotificacion' => 'Remitente',
'destinatarioNotificacion' => 'Destinatario',
'fechaHoraNotificacion' => 'Data',
'asuntoNotificacion' => 'Asunto',
'mensajeNotificacion' => 'Mensaxe',
'Ver Notificacion' => 'Ver Notificación',
 'Insertar Notificacion' => 'Insertar Notificacion',
 'Borrar notificación' => 'Borrar notificación',
 'La notificación fue borrada con éxito.' => 'A notificación foi borrada con éxito.',
 'Remitente' => 'Remitente',
'Asunto' => 'Asunto',
'Fecha' => 'Data',
'Mensaje' => 'Mensaxe',
'Finalizar Sesion' => 'Finalizar Sesión',
'Realizando tabla' => 'TABLA DA SESIÓN',
'Actividad' => 'ACTIVIDADE',
'Crear'=>'Enviar',
 'Enviados' => 'Enviados',
 'Recibidos' => 'Recibidos', 
 'Notificaciones enviadas' => 'Notificacions enviadas',
 'Notificaciones recibidas' => 'Notificacions recibidas',



//SESIONES

'nombreTabla' => 'Táboa',
'nombreActividadIndividual' =>'Actividade',
'idTabla' =>'Táboa',
'idActividadIndividual' => 'Actividade',
'comentarioSesion' => 'Comentario',
'fechaSesion' => 'Data',
'horaInicio' => 'Inicio',
'horaFin' => 'Fin',
'Modificar sesion' => 'Modificar Sesión',
 'Consultar sesiones por fecha' => 'Consultar sesiones por fecha',
 'IniciarSesion' => 'Iniciar sesión',
 'La sesion se ha modificado con éxito.' => 'A sesión modificouse con éxito.',

//GESTION DE EJERCICIOS
'ejercicioname' => 'Nome do Exercicio',
'ejerciciodescription' => 'Descripción do Exercicio',
'gifejercicio' => 'URL para a imaxen GIF do Exercicio',
'previsualizacion' => 'Previsualización do GIF',
'howtoprev' => 'Para previsualizar o GIF, inserte o enlace e pulse Tab',
'saveform' => 'Gardar',
'newejercicio' => 'Insertar Exercicio',
'ejercicionametabla' => 'Nome',
'ejerciciodesctabla' => 'Descripción',
'ejerciciogiftabla' => 'Execución',
'ejerciciomodificar' => 'Modificar',
'ejercicioeliminar' => 'Eliminar',

//GESTION DE TABLAS
'tablaname' => 'Nome da taboa',
'tabladesc' => 'Descripción da taboa',
'savetabla' => 'Gardar',
'newtabla' => 'Insertar Taboa',
'asignartabla' => 'Asignar Exercicios a Taboa',
'seleccionaejercicios' => 'Selecciona Exercicios (ctrl para varios)',
'closetabla' => 'Pechar',
'tablaname2' => 'Nome',
'tabladesc2' => 'Descripción',  
'tablaasignar' => 'Asignar Exercicios',
'tablamodificar' => 'Modificar',
'tablaeliminar' => 'Eliminar',
'Personalizada' => 'Personalizada',
'Estandar' => 'Estandar',
'tablaTipo' => 'Tipo de Táboa',
'tipo' => 'Tipo',
'Tablas' => 'Táboas',
'descripcionTabla' =>'Descripción',
 'AsignarEjercicios'=>'Asinar Exercicios',
 'AñadirEjercicio' => 'Añadir Exercicio',
 'Ejercicio'=>'Exercicio',
 'NumSeries'=>'Núm. Series',
 'NumRepeticiones'=>'Núm. Repeticións',
 'Duracion'=>'Duración',
 'Guardar'=>'Gardar',


 //ACTIVIDADES GRUPALES

'nombreActividadGrupal' => 'Nome Actividade',
'descripcionActividadGrupal' =>'Descripcion',
'numPlazasActividadGrupal' =>'Numero Plazas',
'idActividadGrupal' => 'ID',
'username' => 'Profesor',
'idInstalacion' => 'Instalacion',
'Modificar Actividad Grupal' => 'Modificar Actividade Grupal',
'Insertar Actividad Grupal' => 'Insertar Actividade Grupal',
'Borrar Actividad Grupal' => 'Borrar Actividade Grupal',
'Consultar Actividades Grupales' => 'Consultar Actividades Grupais',
'Ver Actividad Grupal' => 'Ver Actividad Grupal',
'Añadida con exito' => 'Añadida con éxito',
'La actividad grupal fue borrada con éxito' => 'A actividade grupal borrouse con éxito.',
'No se puede borrar porque no existe esa actividad grupal' => 'Esa actividade grupal non existe',
'ActividadesGrupales' => 'Actividades',
'VerMonitor' => 'VerMonitor',
'diaActividadGrupal' => 'Día',
'horaInicioActividadGrupal' => 'Hora Inicio',
'horaFinActividadGrupal' =>'Hora Fin',
'fechaInicioActividadGrupal' => 'Data Inicio',
'fechaFinActividadGrupal' =>'Data Fin',
'La actividad grupal se ha modificado con exito' => 'A actividade grupal modificouse con éxito',
'Ya existe una actividad en esta fecha, instalacion y horario o el monitor esta ocupado' => 'Xa existe unha actividade nesa data, instalación ou horario ou el monitor está ocupado',
'Lunes' => 'Luns',
'Martes' =>'Martes',
'Miércoles' => 'Mércores',
'Jueves'=> 'Xoves',
'Viernes' => 'Venres',
'DesasignarActividad' => 'Desasinar Actividade',

    //ACTIVIDADES INDIVIDUALES

'nombreActividadIndividual' => 'Nome',
'descripcionActividadIndividual' =>'Descricion',
'Modificar Actividad Individual' => 'Modificar Actividade Individual',
'Insertar Actividad Individual' => 'Insertar Actividade Individual',
'Borrar Actividad Individual' => 'Borrar Actividade Individual',
'Consultar Actividades Individuales' => 'Consultar Actividades Individuais',
'Ver Actividad Individual' => 'Ver Actividade Individual',
'La actividad individual fue borrada con exito' => 'A actividade individual foi borrada con exito',
'La actividad individual ya existe en la base de datos' => 'A actividade individual xa existe na base de datos',
'No se puede borrar porque no existe esa actividad individual' => 'Non se pode borrar porque non existe tal actividade individual',
'La actividad individual se ha modificado con exito' => 'A actividade individual modificouse con exito',
  
//ESTADISTICAS    
 'Estadisticas' => 'Estadisticas das sesións do usuario ',   
 'EstadísticasMuevet'=>'Estadísticas do Sistema',
     
 //INSTALACIONES

'nombreInstalacion' => 'Nome',
'descripcionInstalacion' =>'Descricion',
'aforoInstalacion' =>'Aforo',
'idInstalacion' => 'ID',
'Modificar Instalacion' => 'Modificar Instalacion',
'Insertar Instalacion' => 'Insertar Instalacion',
'Borrar Instalacion' => 'Borrar Instalacion',
'Consultar Instalaciones' => 'Consultar Instalacions',
'Ver Instalacion' => 'Ver Instalacion',
'La instalacion fue borrada con exito' => 'A instalacion foi borrada con exito',
'La instalacion ya existe en la base de datos' => 'A instalacion xa existe na base de datos',
'No se puede borrar porque no existe esa instalacion' => 'Non se pode borrar porque non existe esa instalacion',
'La instalacion se ha modificado con exito' => 'A instalacion modificouse con exito',
'No se puede borrar porque no existe esa instalacion' => 'Non se pode eliminar porque a instalación non existe',
    'Añadida con exito'=>'A instalación foi añadida con éxito'

)
?>
